[package]

name = "rgit"
version = "0.1.0"
authors = ["Christian Briones <christian@gmail.com>"]

[dependencies.flate2]
path = "../flate2"

[dependencies]
getopts = "0.2.14"
rust-crypto = "0.2.34"
rustc-serialize = "0.3.16"
nom = "1.1.0"
byteorder = "0.4.2"
hyper = "*"
clap = "1.5.5"
ssh2 = "0.2"
crc = "1.2.0"

[[bin]]
name = "rgit"

