[package]

name = "rgit"
version = "0.0.1"
authors = ["Christian Briones <christian@gmail.com>"]

[dependencies.flate2]
path = "../flate2"

[dependencies]
getopts = "*"
rust-crypto = "*"
rustc-serialize = "*"
nom = "*"
byteorder = "*"

[[bin]]
name = "rgit"

